Mobile layout shops page
TarasOrlovskyi/ReactWaxDeals pull request #34
Opened 2021-09-01 18:11 UTC by Vahtangius

2021-09-02 10:10 UTC, TarasOrlovskyi requested changes

2021-09-02 10:10 UTC, TarasOrlovskyi commented on src/index.css
> +  }
delete it

2021-09-02 10:12 UTC, Rooman commented on src/component/RegistrationPages/SignIn/SignIn.module.css
> +    padding-top: 40px;
Что означают эти знаки вопросов?

2021-09-03 08:00 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/RectangleLine/RectangleLine.jsx
> +      <div className={rectangleLineStyle.contentSignIn__rectangleLine + ' rectangleLine'}>
rectangleLine - why did you use it? I can't find this class in css

2021-09-03 08:00 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/RectangleLine/RectangleLine.module.css
>    display: flex;
i thin that display: flex - unnecessary

2021-09-03 08:00 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/RectangleLine/RectangleLine.module.css
> +}
cool, but for what to use position: relative;?

2021-09-03 08:00 UTC, TarasOrlovskyi commented on src/component/Stores/Stores.module.css
> +  }
I think that you need set up for @media -> .shopsContent { padding: -25px 0; }

2021-09-03 08:41 UTC, TarasOrlovskyi approved these changes

2021-09-03 08:47 UTC, TarasOrlovskyi approved these changes

2021-09-03 08:47 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/SignIn.module.css
> +    padding-top: 40px;
это больше для себя писал, так как планировал еще созваниваться и смотреть на его мониторе как отображается

2021-09-03 08:48 UTC, merged