Layout all pages according design
TarasOrlovskyi/ReactWaxDeals pull request #35
Opened 2021-09-06 21:56 UTC by BogdanParashchak

2021-09-07 07:19 UTC, TarasOrlovskyi requested changes

2021-09-07 07:19 UTC, TarasOrlovskyi commented on src/component/Common/FormsControl/FormControl.module.css
> +}
I think in we can put width: 100% in this class in order to error message will be flexible

2021-09-07 07:19 UTC, TarasOrlovskyi commented on src/component/Contact/ContactUs.module.css
> +
delete empty space

2021-09-07 07:19 UTC, TarasOrlovskyi commented on src/component/Contact/ContactUsForm/ContactUsForm.jsx
> +            <div className={userStyle.user__fields/* + ' ' + contactStyle.contactUsPageUser__fields*/}>
delete all comments

2021-09-07 07:19 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/SignIn.module.css
>  }
you should delete empty class

2021-09-07 07:19 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/SignIn.module.css
> +    padding: 70px 0;*/
delete comments

2021-09-07 07:19 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/SignIn.module.css
> +    /*height: 17.78em;*/
delete all comments

2021-09-07 07:19 UTC, TarasOrlovskyi commented on src/index.css
> +
delete empty space

2021-09-07 07:26 UTC, BogdanParashchak commented on src/component/Contact/ContactUs.module.css
> +
done

2021-09-07 07:27 UTC, BogdanParashchak commented on src/component/Contact/ContactUsForm/ContactUsForm.jsx
> +            <div className={userStyle.user__fields/* + ' ' + contactStyle.contactUsPageUser__fields*/}>
done

2021-09-07 07:29 UTC, BogdanParashchak commented on src/component/RegistrationPages/SignIn/SignIn.module.css
>  }
done

2021-09-07 07:29 UTC, BogdanParashchak commented on src/component/RegistrationPages/SignIn/SignIn.module.css
> +    padding: 70px 0;*/
done

2021-09-07 07:30 UTC, BogdanParashchak commented on src/component/RegistrationPages/SignIn/SignIn.module.css
> +    /*height: 17.78em;*/
done

2021-09-07 07:30 UTC, BogdanParashchak commented on src/index.css
> +
done

2021-09-07 07:43 UTC, BogdanParashchak commented on src/component/Common/FormsControl/FormControl.module.css
> +}
done

2021-09-08 08:11 UTC, TarasOrlovskyi approved these changes

2021-09-08 08:12 UTC, merged