Login page
TarasOrlovskyi/ReactWaxDeals pull request #5
Opened 2021-07-15 15:21 UTC by airavata-elephant

2021-07-15 17:22 UTC, TarasOrlovskyi requested changes

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/RectangleLine/RectangleLine.jsx
> +
delete empty row

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/RectangleLine/RectangleLine.jsx
> +
delete empty row

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/RectangleLine/RectangleLine.jsx
> +
delete empty row

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/RectangleLine/RectangleLine.jsx
> +    return   <div className={s.contentSignIn__rectangleLine + ' rectangleLine'}>
you should put your jsx code in (). I mean write return with '()' - 

return (
  <div.......
);

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/SignIn.module.css
> +
delete empty row

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/User.module.css
> +/* webkit */
this comment should be above the previous class

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/User.module.css
> +/* Firefox 19+ */
this comment should be above the previous class

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/User.module.css
> +/* Firefox 18- */
this comment should be above the previous class

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/User.module.css
> +/* IE */
this comment should be above the previous class

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/User.module.css
> +/* webkit */
this comment should be above the previous class

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/User.module.css
> +/* Firefox 19+ */
this comment should be above the previous class

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/User.module.css
> +/* Firefox 18- */
this comment should be above the previous class

2021-07-15 17:22 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/User.module.css
> +/* IE */
this comment should be above the previous class

2021-07-15 18:31 UTC, Vahtangius submitted a review, later dismissed

2021-07-16 13:18 UTC, TarasOrlovskyi requested changes

2021-07-16 13:18 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/RectangleLine/RectangleLine.jsx
> +    );
ctrl + alt + L

2021-07-16 13:18 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/RectangleLine/RectangleLine.jsx
> +import rectangleLine from "../../../../assets/img/socialNetwork/Rectangle-line.png";
Rectangle-line.png => rectangle-line.png

2021-07-16 13:18 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/SignIn.jsx
> +import s from "./SignIn.module.css";
change 's' to signInStyle and refactor in all file

2021-07-16 13:18 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/SignIn/SocialNetwork/SocialNetwork.jsx
> +import s from "./SocialNetwork.module.css";
change 's' to socialNetworkStyle and refactor all file

2021-07-16 13:18 UTC, TarasOrlovskyi commented on src/component/RegistrationPages/User.module.css
> +/* webkit */
did you change it?

2021-07-16 13:21 UTC, Vahtangius submitted a review, later dismissed

2021-07-16 13:24 UTC, airavata-elephant commented on src/component/RegistrationPages/User.module.css
> +/* webkit */
yes boss

2021-07-16 14:08 UTC, TarasOrlovskyi approved these changes

2021-07-16 14:08 UTC, Vahtangius approved these changes

2021-07-16 14:10 UTC, merged